controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

get_filieres:
    path: '/get_filieres'
    controller: App\Controller\NoteController::getFilieres
get_groupes:
    path: '/get_groupes'
    controller: App\Controller\NoteController::getGroupes
export_data:
    path: '/export'
    controller: App\Controller\NoteController::exportData